obstacle_range: 2.5
raytrace_range: 3.0
min_obstacle_height: -1.0
footprint: [[0.25,0.25],[0.25,-0.25],[-0.25,-0.25],[-0.25,0.25]]
inflation_radius: 0.65

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}

