local_costmap:
  global_frame: odom
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  raytrace_range: 3.0
  rolling_window: true
  width: 6.0
  height: 6.0
  inflation_radius: 0.35
  resolution: 0.05

